export default async function handler(req, res) {
  const { code, state, error } = req.query;

  // state is a CSRF nonce generated by the extension. The extension opens auth
  // in a normal tab and watches for the tab to land on our own result page, so
  // we redirect there (carrying the nonce back for it to verify) rather than to
  // an extension-owned URL.
  const nonce = state ?? '';
  if (!/^[A-Za-z0-9-]{8,}$/.test(nonce)) {
    return res.status(400).send('Invalid state parameter');
  }

  const serverUrl = process.env.SERVER_URL ?? `https://${req.headers.host}`;
  const resultUrl = (params) =>
    `${serverUrl}/api/oauth/result?${new URLSearchParams({ ...params, state: nonce })}`;

  if (error) {
    return res.redirect(302, resultUrl({ error }));
  }
  if (!code) {
    return res.redirect(302, resultUrl({ error: 'missing_code' }));
  }

  const tokenRes = await fetch('https://slack.com/api/oauth.v2.access', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: process.env.SLACK_CLIENT_ID,
      client_secret: process.env.SLACK_CLIENT_SECRET,
      code,
      redirect_uri: `${serverUrl}/api/oauth/callback`,
    }),
  });

  const data = await tokenRes.json();

  if (!data.ok) {
    return res.redirect(302, resultUrl({ error: data.error }));
  }

  // Remove ALLOWED_TEAM_ID from Vercel env vars to open up to any workspace.
  if (process.env.ALLOWED_TEAM_ID && data.team?.id !== process.env.ALLOWED_TEAM_ID) {
    return res.redirect(302, resultUrl({ error: 'wrong_workspace' }));
  }

  const token = data.authed_user?.access_token;
  const team = data.team?.name ?? '';

  return res.redirect(302, resultUrl({ token, team }));
}
